[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Build settings
  NEXT_USE_TURBOPACK = "false"  # Disable Turbopack for Netlify builds
  NODE_VERSION = "20.12.2"  # Using Node.js 20 LTS for Next.js compatibility
  NPM_FLAGS = "--legacy-peer-deps"  # Helps with dependency resolution
  
  # Required environment variables for build
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[functions]
  node_bundler = "esbuild"  # Use esbuild for faster builds

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
